services:
  home-assistant:
    image: linuxserver/homeassistant:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bijgaardehub.rule=Host(`bijgaardehub.lenders.dev`)"
      - "traefik.http.routers.bijgaardehub.tls=true"
      - "traefik.http.routers.bijgaardehub.tls.certresolver=myresolver"

  mosquitto:
    image: eclipse-mosquitto
    user: $PUID:$PGID
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
    env_file:
      - .env
    ports:
      - 1883:1883
      - 9001:9001
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf", "-v"]
