services:
  home-assistant:
    image: linuxserver/homeassistant:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
    ports:
      - "8123:8123"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bijgaardehub.rule=Host(`bijgaardehub.lenders.dev`)"
      - "traefik.http.routers.bijgaardehub.tls=true"
      - "traefik.http.routers.bijgaardehub.tls.certresolver=myresolver"
