services:
  home-assistant:
    image: linuxserver/homeassistant:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bijgaardehub.rule=Host(`hub.bijgaardehof.be`) || Host(`bijgaardehub.lenders.dev`)"
      - "traefik.http.routers.bijgaardehub.tls=true"
      - "traefik.http.routers.bijgaardehub.tls.certresolver=myresolver"
    healthcheck:
      test: curl --silent --fail http://localhost:8123/
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  mosquitto:
    image: eclipse-mosquitto
    user: $PUID:$PGID
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
    env_file:
      - .env
    ports:
      - 1883:1883
      - 9001:9001
    command: [ "/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf", "-v" ]
    healthcheck:
      test: nc -z 0.0.0.0 1883
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  unhealthy-restarter:
    image: docker:cli
    network_mode: none
    cap_drop:
      - ALL
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 60; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done" ]
    restart: unless-stopped
