- method: GET
  resource: https://qbus-scraper.lenders.dev/data
  authentication: basic
  username: !secret qbus_username
  password: !secret qbus_password
  scan_interval: 60
  timeout: 60
  sensor:
    - name: Rainwater tanks - Spore - Level
      unique_id: rainwater_tanks.spore.level
      value_template: '{{ value_json["L1 Spore"] }}'
      unit_of_measurement: cm
      state_class: measurement
    - name: Rainwater tanks - Spore - Relative level
      unique_id: rainwater_tanks.spore.relative
      value_template: '{{ (value_json["L1 Spore"] / 300 * 100) | round }}'
      unit_of_measurement: '%'
      state_class: measurement
    - name: Rainwater tanks - Spore - Volume
      unique_id: rainwater_tanks.spore.volume
      value_template: '{{ (value_json["L1 Spore"] / 300 * 10e3) | round }}'
      device_class: volume_storage
      unit_of_measurement: L
      state_class: measurement
    - name: Rainwater tanks - Spore - Max
      unique_id: rainwater_tanks.spore.max
      value_template: '{{ 300 }}'
      unit_of_measurement: cm
      state_class: measurement

    - name: Rainwater tanks - Wijgaard - Level
      unique_id: rainwater_tanks.wijgaard.level
      value_template: '{{ value_json["L2 Wijgaard"] }}'
      unit_of_measurement: cm
      state_class: measurement
    - name: Rainwater tanks - Wijgaard - Relative level
      unique_id: rainwater_tanks.wijgaard.relative
      value_template: '{{ (value_json["L2 Wijgaard"] / 300 * 100) | round }}'
      unit_of_measurement: '%'
      state_class: measurement
    - name: Rainwater tanks - Wijgaard - Volume
      unique_id: rainwater_tanks.wijgaard.volume
      value_template: '{{ (value_json["L2 Wijgaard"] / 300 * 20e3) | round }}'
      device_class: volume_storage
      unit_of_measurement: L
      state_class: measurement
    - name: Rainwater tanks - Wijgaard - Max
      unique_id: rainwater_tanks.wijgaard.max
      value_template: '{{ 300 }}'
      unit_of_measurement: cm
      state_class: measurement

    - name: Rainwater tanks - Biotope - Level
      unique_id: rainwater_tanks.biotope.level
      value_template: '{{ value_json["L3 Biotope"] }}'
      unit_of_measurement: cm
      state_class: measurement
    - name: Rainwater tanks - Biotope - Relative level
      unique_id: rainwater_tanks.biotope.relative
      value_template: '{{ (value_json["L3 Biotope"] / 300 * 100) | round }}'
      unit_of_measurement: '%'
      state_class: measurement
    - name: Rainwater tanks - Biotope - Volume
      unique_id: rainwater_tanks.biotope.volume
      value_template: '{{ (value_json["L3 Biotope"] / 300 * 20e3) | round }}'
      device_class: volume_storage
      unit_of_measurement: L
      state_class: measurement
    - name: Rainwater tanks - Biotope - Max
      unique_id: rainwater_tanks.biotope.max
      value_template: '{{ 300 }}'
      unit_of_measurement: cm
      state_class: measurement

    - name: Rainwater tanks - Hubo - Level
      unique_id: rainwater_tanks.hubo.level
      value_template: '{{ value_json["L5 Hubo"] }}'
      unit_of_measurement: cm
      state_class: measurement
    - name: Rainwater tanks - Hubo - Relative level
      unique_id: rainwater_tanks.hubo.relative
      value_template: '{{ (value_json["L5 Hubo"] / 300 * 100) | round }}'
      unit_of_measurement: '%'
      state_class: measurement
    - name: Rainwater tanks - Hubo - Volume
      unique_id: rainwater_tanks.hubo.volume
      value_template: '{{ (value_json["L5 Hubo"] / 300 * 150e3) | round }}'
      device_class: volume_storage
      unit_of_measurement: L
      state_class: measurement
    - name: Rainwater tanks - Hubo - Max
      unique_id: rainwater_tanks.hubo.max
      value_template: '{{ 300 }}'
      unit_of_measurement: cm
      state_class: measurement

  binary_sensor:
    - name: Rainwater tanks - Spore - Valve
      unique_id: rainwater_tanks.spore.valve
      value_template: '{{ value_json["K1 Spore open"] }}'
      device_class: opening
    - name: Rainwater tanks - Wijgaard - Valve
      unique_id: rainwater_tanks.wijgaard.valve
      value_template: '{{ value_json["K2 Wijgaard open"] }}'
      device_class: opening
    - name: Rainwater tanks - Biotope - Valve
      unique_id: rainwater_tanks.biotope.valve
      value_template: '{{ value_json["K3 Biotope open"] }}'
      device_class: opening
    - name: Rainwater tanks - Wadi - Valve
      unique_id: rainwater_tanks.wadi.valve
      value_template: '{{ value_json["K4 Wadi 1 cohousing open"] }}'
      device_class: opening
    - name: Rainwater tanks - Baertsoen-Buysse - Pump
      unique_id: rainwater_tanks.spore.pump
      value_template: '{{ value_json["P1 Pomp Baertsoen Buysse"] }}'
      device_class: power
    - name: Rainwater tanks - Automation
      unique_id: rainwater_tanks.automation.status
      value_template: '{{ value_json["Automatisering kleppen en pomp"] }}'
      device_class: power
