
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest: !include_dir_merge_list rest

desigo:
  url: https://desigo-scraper.lenders.dev/data
  username: !secret desigo_username
  password: !secret desigo_password
  data_series:
    - key: biotope_aanvoer_primair
      name: Biotope - Warmtepomp aanvoertemperatuur primair
      series_group: Biotope
      series_name: Verwarming'Warmtepomp'Aanv.temp.primair
      device_class: temperature
      unit_of_measurement: °C
    - key: biotope_retour_primair
      name: Biotope - Warmtepomp retourtemperatuur primair
      series_group: Biotope
      series_name: Verwarming'Warmtepomp'Primaire retourtemp.
      device_class: temperature
      unit_of_measurement: °C
